### ISSUE TITLE
Failed to transform kediatr-core-1.0.13.jar using Jetifier

### ISSUE THREAD

**Issue by mikepattyn** [Trendyol/kediatR#10]
Hi, 

Im getting this error message: 

`Failed to transform '/Users/****/.gradle/caches/modules-2/files-2.1/com.trendyol/kediatr-core/1.0.13/f17dc35dc9a8f944917acf14dd006b9d811f1ae9/kediatr-core-1.0.13.jar' using Jetifier. Reason: null. (Run with --stacktrace for more details.)
`

Havent been able to get the stracktrace for more details passing the parameter, so sorry for that.

Greetings

**Comment by Phattboyslim** [comment]
Downgrading to version 1.0.12 and i dont get the error anymore :)
