### ISSUE TITLE
An exception is thrown using Java 11

### ISSUE THREAD

**Issue by gustavodaquino** [Trendyol/kediatR#14]
**Excepcted Behavior**

Can I use this library in a SpringBoot application compiled by JDK 11?

**Current Behavior**

An exception is thrown because the compiled version of the library is 57.0.
.
> Caused by: java.lang.UnsupportedClassVersionError: com/trendyol/kediatr/spring/KediatrConfiguration has been compiled by a more recent version of the Java Runtime (class file version 57.0), this version of the Java Runtime only recognizes class file versions up to 55.0.

**Steps to Reproduce**

Simple run a SpringBoot application using the JDK **11.0.11.hs-adpt**.

**Context (Environment)**

kediatR-spring-starter version: 1.0.14
IntelliJ version: 2020.3
Spring Boot 2.4.1
Kotlin version 1.4.21
Java Runtime version: 11.0.11+9
Java class version: 55.0

**Comment by bilal-kilic** [comment]
Hi, we actually fixed this issue but there was a problem releasing it. Can you please try again with kediatr-spring-starter:1.0.15

**Comment by gustavodaquino** [comment]
Off course I should try, but this version is not release yet, is it correct?

**Comment by gustavodaquino** [comment]
Off course I will try, but this version is not release yet, is it correct?

**Comment by bilal-kilic** [comment]
I released it today but it takes some time for new images to be accessible in maven repository. You should be able to access it in a couple of hours

**Comment by gustavodaquino** [comment]
@bilal-kilic, it worked like a charm 🥳. Thanks for the help!
