### ISSUE TITLE
Bug - Instance will not create when has constructor parameters

### ISSUE THREAD

**Issue by oguzhaneren** [Trendyol/kediatR#2]
https://github.com/Trendyol/kediatR/blob/423e2791c37e4920d577c06531e0982de9aec3ca/kediatr-core/src/main/kotlin/com/trendyol/kediatr/RegistryImpl.kt#L26

https://github.com/Trendyol/kediatR/blob/423e2791c37e4920d577c06531e0982de9aec3ca/kediatr-core/src/main/kotlin/com/trendyol/kediatr/RegistryImpl.kt#L40

**Comment by CanerPatir** [comment]
Hi Oguzhan, in core usage there is no IoC container and dependency resolution  mechansim. So, we can not resolve dependency tree of handler. You can use spring package if you’d like to cover this case. By the way, if you have any idea about resolving dependency tree of handler without IoC container, the repository is open to contribution. Please feel free to open pull request. However, we can not label the issue as a bug. For now, I am changing the status of issue to closed.
