### ISSUE TITLE
Pipeline Behavior postProcess function with handlers result

### ISSUE THREAD

**Issue by dagliberkay** [Trendyol/kediatR#33]
In the "postProcess" function in Pipeline behavior, only the request in the handler comes as a parameter. But here we can also take the handler's response as a parameter.

In current version, In order to get the response in the "postProcess" function, I need to set the response to a parameter in the request in the handler.

Without the need for it, the pipeline behavior can do this.

I opened a pull request for this job. However, making this transition will require people using the existing project to update their code during the transition to the new version.

https://github.com/Trendyol/kediatR/pull/32

What do you think about this development? Can another approach be made or can we think of another method for this?

**Comment by dagliberkay** [comment]
Also added the same thing for the v2 

https://github.com/Trendyol/kediatR/pull/34

**Comment by osoykan** [comment]
Superseded by #31.
