### ISSUE TITLE
Command, Query and Notification Pipeline Segregation

### ISSUE THREAD

**Issue by rozturac** [Trendyol/kediatR#36]
Hi, while developing on The [PR](https://github.com/Trendyol/kediatR/pull/35), it occurred to me that there might be different pipeline behaviors for Command, Query, and Notification. If you agree, I would like to make this development with pleasure.

**Comment by osoykan** [comment]
Hi, thanks for the suggestion, it could be, but I think not necessary much since you can achieve the same behavior within the pipeline by pattern matching.

If I give a pseudo example:

```kotlin
abstract class BranchedPipelineBehaviour: PipelineBehaviour {
 override fun handle(req: TReqeust, next: RequestHandlerDelegate) : TResponse {
      when(req) {
         is Notification -> handleNotification(req, next)
         is Command -> handleCommand(req,next)
         is Query -> handleQuery(req,next)
     }

 abstract fun handleNotification(req, next): TResponse
 abstract fun handleCommand(req, next): TResponse 
 abstract fun handleQuery(req, next): TResponse

}
```

**Comment by rozturac** [comment]
Hi, Thanks for reply. As you said, it seems not essential to make this development. Thanks again for the suggestion 🙏
